# theme: jekyll-theme-minimal
remote_theme: pages-themes/tactile@v0.2.0
title: Artwork by Pete Rumble - yaml
description: Showcasing my artwork for all to see. Please get in if you would like to purchase a print or arrange an exhibition.
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
